/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
#include "CryptoContext.h"
/* Header for class info_androidhive_webmobilegroupchat_JniUtils */

#ifndef _Included_info_androidhive_webmobilegroupchat_JniUtils
#define _Included_info_androidhive_webmobilegroupchat_JniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     info_androidhive_webmobilegroupchat_JniUtils
 * Method:    nativeCreateCryptoContext
 * Signature: (Ljava/lang/String;II)J
 */
JNIEXPORT jlong JNICALL Java_info_androidhive_webmobilegroupchat_JniUtils_nativeCreateCryptoContext
  (JNIEnv *, jclass, jstring, jint, jint);

/*
 * Class:     info_androidhive_webmobilegroupchat_JniUtils
 * Method:    nativeReleaseCryptoContext
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_info_androidhive_webmobilegroupchat_JniUtils_nativeReleaseCryptoContext
  (JNIEnv *, jclass, jlong);

/*
 * Class:     info_androidhive_webmobilegroupchat_JniUtils
 * Method:    nativeEncrypt
 * Signature: (J[DLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_info_androidhive_webmobilegroupchat_JniUtils_nativeEncrypt
  (JNIEnv *, jclass, jlong, jdoubleArray, jstring);

/*
 * Class:     info_androidhive_webmobilegroupchat_JniUtils
 * Method:    nativeDecrypt
 * Signature: (JLjava/lang/String;)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_info_androidhive_webmobilegroupchat_JniUtils_nativeDecrypt
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     info_androidhive_webmobilegroupchat_JniUtils
 * Method:    nativeLoadLocalKeys
 * Signature: (JLjava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_info_androidhive_webmobilegroupchat_JniUtils_nativeLoadLocalKeys
  (JNIEnv *, jclass, jlong, jstring, jstring);

/*
 * Class:     info_androidhive_webmobilegroupchat_JniUtils
 * Method:    nativeGenerateKeys
 * Signature: (JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
//JNIEXPORT jstring JNICALL Java_info_androidhive_webmobilegroupchat_JniUtils_nativeGenerateKeys
//  (JNIEnv *, jclass, jlong, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
